# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.x
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        # Add hamburger menu button
        self.btn_menu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_menu.setObjectName("btn_menu")
        self.btn_menu.setText("☰")
        self.btn_menu.setStyleSheet("text-align: left; padding: 5px;")
        self.verticalLayout.addWidget(self.btn_menu)

        # Display
        self.display = QtWidgets.QLineEdit(self.centralwidget)
        self.display.setObjectName("display")
        self.verticalLayout.addWidget(self.display)

        # Advanced operations
        self.advancedLayout = QtWidgets.QHBoxLayout()
        self.btn_sqrt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sqrt.setObjectName("btn_sqrt")
        self.btn_sqrt.setText("√")
        self.advancedLayout.addWidget(self.btn_sqrt)
        
        self.btn_pow = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pow.setObjectName("btn_pow")
        self.btn_pow.setText("x²")
        self.advancedLayout.addWidget(self.btn_pow)
        
        self.btn_log = QtWidgets.QPushButton(self.centralwidget)
        self.btn_log.setObjectName("btn_log")
        self.btn_log.setText("log")
        self.advancedLayout.addWidget(self.btn_log)
        
        self.verticalLayout.addLayout(self.advancedLayout)

        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 0, 0, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 0, 1, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 0, 2, 1, 1)
        self.btn_divide = QtWidgets.QPushButton(self.centralwidget)
        self.btn_divide.setObjectName("btn_divide")
        self.gridLayout.addWidget(self.btn_divide, 0, 3, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 1, 0, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 1, 1, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 1, 2, 1, 1)
        self.btn_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.btn_multiply.setObjectName("btn_multiply")
        self.gridLayout.addWidget(self.btn_multiply, 1, 3, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 2, 0, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 2, 1, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 2, 2, 1, 1)
        self.btn_subtract = QtWidgets.QPushButton(self.centralwidget)
        self.btn_subtract.setObjectName("btn_subtract")
        self.gridLayout.addWidget(self.btn_subtract, 2, 3, 1, 1)
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setObjectName("btn_0")
        self.gridLayout.addWidget(self.btn_0, 3, 0, 1, 1)
        self.btn_decimal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decimal.setObjectName("btn_decimal")
        self.gridLayout.addWidget(self.btn_decimal, 3, 1, 1, 1)
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout.addWidget(self.btn_add, 3, 2, 1, 1)
        self.btn_equals = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equals.setObjectName("btn_equals")
        self.gridLayout.addWidget(self.btn_equals, 3, 3, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.btn_clear, 4, 0, 1, 2)
        self.btn_add_transaction = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_transaction.setObjectName("btn_add_transaction")
        self.gridLayout.addWidget(self.btn_add_transaction, 4, 2, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Calculator"))
        self.display.setPlaceholderText(_translate("MainWindow", "0"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_divide.setText(_translate("MainWindow", "/"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_multiply.setText(_translate("MainWindow", "*"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_subtract.setText(_translate("MainWindow", "-"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_decimal.setText(_translate("MainWindow", "."))
        self.btn_add.setText(_translate("MainWindow", "+"))
        self.btn_equals.setText(_translate("MainWindow", "="))
        self.btn_clear.setText(_translate("MainWindow", "C"))
        self.btn_add_transaction.setText(_translate("MainWindow", "Add Transaction"))
        self.btn_menu.setText(_translate("MainWindow", "☰"))
        self.btn_sqrt.setText(_translate("MainWindow", "√"))
        self.btn_pow.setText(_translate("MainWindow", "x²"))
        self.btn_log.setText(_translate("MainWindow", "log"))
